name: deploy-py-lambda
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: arthiondaena/py-lambda-deploy@v1.0
      with:
        lambda_layer_arn: 'arn:aws:lambda:us-east-1:669386429143:layer:search-places'
        lambda_function_name: 'arn:aws:lambda:us-east-1:669386429143:function:search_places_test'
        python_version: '3.12'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'